export interface Topic {
  name: string;
  description: string;
}

export interface Module {
  title: string;
  topics: Topic[];
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  estimatedHours: number;
}

export interface LanguageSyllabus {
  id: string;
  name: string;
  icon: string;
  color: string;
  gradient: string;
  tagline: string;
  description: string;
  modules: Module[];
  totalHours: number;
  prerequisites: string[];
}

export const syllabusData: LanguageSyllabus[] = [
  {
    id: "c",
    name: "C",
    icon: "🔧",
    color: "#A8B9CC",
    gradient: "from-slate-500 to-blue-600",
    tagline: "The Foundation of Modern Computing",
    description: "Master the language that powers operating systems, embedded devices, and high-performance applications. C gives you unmatched control over hardware and memory.",
    prerequisites: ["Basic computer literacy", "Understanding of number systems"],
    totalHours: 80,
    modules: [
      {
        title: "Introduction to C Programming",
        difficulty: "Beginner",
        estimatedHours: 8,
        topics: [
          { name: "History & Evolution of C", description: "Origins, ANSI C, C99, C11, C17 standards" },
          { name: "Setting Up Environment", description: "GCC, Clang, IDEs, compiling & linking" },
          { name: "First C Program", description: "Hello World, main function, return values" },
          { name: "Compilation Process", description: "Preprocessing, compilation, assembly, linking" },
        ],
      },
      {
        title: "Data Types & Variables",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: "Primitive Data Types", description: "int, float, double, char, void" },
          { name: "Type Modifiers", description: "short, long, signed, unsigned" },
          { name: "Constants & Literals", description: "const, #define, enum, literal types" },
          { name: "Type Casting", description: "Implicit and explicit conversions" },
          { name: "Storage Classes", description: "auto, register, static, extern" },
        ],
      },
      {
        title: "Control Flow",
        difficulty: "Beginner",
        estimatedHours: 8,
        topics: [
          { name: "Conditional Statements", description: "if, if-else, nested if, switch-case" },
          { name: "Loops", description: "for, while, do-while, nested loops" },
          { name: "Jump Statements", description: "break, continue, goto, return" },
          { name: "Operators", description: "Arithmetic, relational, logical, bitwise, ternary" },
        ],
      },
      {
        title: "Functions",
        difficulty: "Intermediate",
        estimatedHours: 10,
        topics: [
          { name: "Function Declaration & Definition", description: "Prototypes, parameters, return types" },
          { name: "Parameter Passing", description: "Call by value vs call by reference" },
          { name: "Recursion", description: "Recursive functions, stack overflow, tail recursion" },
          { name: "Variadic Functions", description: "Functions with variable arguments" },
          { name: "Inline Functions", description: "Performance optimization with inline" },
        ],
      },
      {
        title: "Pointers & Memory Management",
        difficulty: "Advanced",
        estimatedHours: 14,
        topics: [
          { name: "Pointer Basics", description: "Declaration, dereferencing, pointer arithmetic" },
          { name: "Pointers & Arrays", description: "Array-pointer relationship, pointer arrays" },
          { name: "Dynamic Memory", description: "malloc, calloc, realloc, free" },
          { name: "Function Pointers", description: "Callbacks, jump tables" },
          { name: "Double Pointers", description: "Pointer to pointer, dynamic 2D arrays" },
          { name: "Memory Leaks & Debugging", description: "Valgrind, common pitfalls" },
        ],
      },
      {
        title: "Structures & Unions",
        difficulty: "Intermediate",
        estimatedHours: 8,
        topics: [
          { name: "Structures", description: "Definition, initialization, nested structures" },
          { name: "Unions", description: "Memory sharing, use cases" },
          { name: "Typedef", description: "Type aliases for readability" },
          { name: "Bit Fields", description: "Memory-efficient flag storage" },
        ],
      },
      {
        title: "File I/O & Preprocessor",
        difficulty: "Intermediate",
        estimatedHours: 8,
        topics: [
          { name: "File Operations", description: "fopen, fclose, fread, fwrite, fprintf, fscanf" },
          { name: "Binary Files", description: "Reading/writing binary data" },
          { name: "Preprocessor Directives", description: "#include, #define, #ifdef, macros" },
          { name: "Header Files", description: "Creating & using header files, include guards" },
        ],
      },
      {
        title: "Advanced C Concepts",
        difficulty: "Advanced",
        estimatedHours: 14,
        topics: [
          { name: "Data Structures in C", description: "Linked lists, stacks, queues, trees" },
          { name: "Multithreading", description: "POSIX threads, mutexes, synchronization" },
          { name: "Socket Programming", description: "TCP/UDP, client-server model" },
          { name: "Makefile & Build Systems", description: "Automating compilation with make, CMake" },
        ],
      },
    ],
  },
  {
    id: "python",
    name: "Python",
    icon: "🐍",
    color: "#3776AB",
    gradient: "from-blue-500 to-yellow-500",
    tagline: "Versatile, Readable, Powerful",
    description: "From web development to AI/ML, data science to automation — Python is the world's most popular programming language for good reason.",
    prerequisites: ["Basic computer literacy"],
    totalHours: 90,
    modules: [
      {
        title: "Python Fundamentals",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: "Python Setup & REPL", description: "Installation, virtual environments, pip" },
          { name: "Variables & Data Types", description: "int, float, str, bool, None, type inference" },
          { name: "Operators & Expressions", description: "Arithmetic, comparison, logical, walrus operator" },
          { name: "String Operations", description: "f-strings, slicing, methods, formatting" },
          { name: "Input/Output", description: "print(), input(), file I/O basics" },
        ],
      },
      {
        title: "Control Structures",
        difficulty: "Beginner",
        estimatedHours: 8,
        topics: [
          { name: "Conditionals", description: "if, elif, else, match-case (3.10+)" },
          { name: "Loops", description: "for, while, break, continue, else clause" },
          { name: "Comprehensions", description: "List, dict, set, generator comprehensions" },
          { name: "Exception Handling", description: "try, except, finally, raise, custom exceptions" },
        ],
      },
      {
        title: "Data Structures",
        difficulty: "Beginner",
        estimatedHours: 12,
        topics: [
          { name: "Lists", description: "Creation, slicing, methods, nested lists" },
          { name: "Tuples & Named Tuples", description: "Immutability, unpacking, collections.namedtuple" },
          { name: "Dictionaries", description: "CRUD operations, defaultdict, OrderedDict" },
          { name: "Sets & Frozensets", description: "Set operations, membership testing" },
          { name: "Collections Module", description: "Counter, deque, ChainMap" },
        ],
      },
      {
        title: "Functions & Modules",
        difficulty: "Intermediate",
        estimatedHours: 10,
        topics: [
          { name: "Function Basics", description: "def, return, default args, *args, **kwargs" },
          { name: "Lambda & Higher-Order", description: "Lambda, map, filter, reduce, closures" },
          { name: "Decorators", description: "Function decorators, class decorators, functools" },
          { name: "Generators & Iterators", description: "yield, generator expressions, itertools" },
          { name: "Modules & Packages", description: "import system, __init__.py, relative imports" },
        ],
      },
      {
        title: "Object-Oriented Python",
        difficulty: "Intermediate",
        estimatedHours: 12,
        topics: [
          { name: "Classes & Objects", description: "Attributes, methods, __init__, self" },
          { name: "Inheritance", description: "Single, multiple, MRO, super()" },
          { name: "Magic Methods", description: "__str__, __repr__, __eq__, __hash__, __len__" },
          { name: "Properties & Descriptors", description: "@property, getter/setter, descriptors" },
          { name: "Abstract Classes", description: "ABC module, abstract methods, interfaces" },
          { name: "Dataclasses", description: "@dataclass, field(), frozen, slots" },
        ],
      },
      {
        title: "File Handling & OS",
        difficulty: "Intermediate",
        estimatedHours: 8,
        topics: [
          { name: "File I/O", description: "open(), read, write, context managers" },
          { name: "CSV & JSON", description: "csv module, json module, serialization" },
          { name: "OS & Path", description: "os module, pathlib, file system operations" },
          { name: "Regular Expressions", description: "re module, patterns, groups, substitution" },
        ],
      },
      {
        title: "Advanced Python",
        difficulty: "Advanced",
        estimatedHours: 14,
        topics: [
          { name: "Concurrency", description: "threading, multiprocessing, asyncio, GIL" },
          { name: "Type Hints", description: "typing module, mypy, Protocol, generics" },
          { name: "Metaclasses", description: "type(), __new__, __init_subclass__" },
          { name: "Context Managers", description: "Custom context managers, contextlib" },
          { name: "Testing", description: "unittest, pytest, mocking, fixtures" },
        ],
      },
      {
        title: "Python Ecosystem",
        difficulty: "Advanced",
        estimatedHours: 16,
        topics: [
          { name: "Web Development", description: "Flask, Django, FastAPI fundamentals" },
          { name: "Data Science Basics", description: "NumPy, Pandas, Matplotlib intro" },
          { name: "Database Integration", description: "SQLite, SQLAlchemy, ORM patterns" },
          { name: "API Development", description: "REST APIs, authentication, deployment" },
        ],
      },
    ],
  },
  {
    id: "java",
    name: "Java",
    icon: "☕",
    color: "#ED8B00",
    gradient: "from-orange-500 to-red-600",
    tagline: "Write Once, Run Anywhere",
    description: "Enterprise-grade programming with strong typing, robust OOP, and the massive JVM ecosystem. The backbone of Android and enterprise applications.",
    prerequisites: ["Basic programming concepts", "Understanding of OOP theory"],
    totalHours: 100,
    modules: [
      {
        title: "Java Fundamentals",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: "Java Ecosystem", description: "JDK, JRE, JVM, bytecode, platform independence" },
          { name: "Setup & First Program", description: "Installation, IDEs, Hello World, main method" },
          { name: "Primitive Types", description: "byte, short, int, long, float, double, char, boolean" },
          { name: "Variables & Operators", description: "Declaration, assignment, arithmetic, logical" },
          { name: "Type Casting", description: "Widening, narrowing, autoboxing, unboxing" },
        ],
      },
      {
        title: "Control Flow & Arrays",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: "Conditionals", description: "if-else, switch (traditional & enhanced)" },
          { name: "Loops", description: "for, enhanced for, while, do-while, labels" },
          { name: "Arrays", description: "1D, 2D, jagged arrays, Arrays utility class" },
          { name: "Strings", description: "String, StringBuilder, StringBuffer, methods" },
          { name: "Scanner & I/O", description: "Console input, formatted output" },
        ],
      },
      {
        title: "Object-Oriented Programming",
        difficulty: "Intermediate",
        estimatedHours: 14,
        topics: [
          { name: "Classes & Objects", description: "Fields, methods, constructors, this keyword" },
          { name: "Encapsulation", description: "Access modifiers, getters/setters, packages" },
          { name: "Inheritance", description: "extends, super, method overriding, final" },
          { name: "Polymorphism", description: "Runtime vs compile-time, method overloading" },
          { name: "Abstract Classes", description: "Abstract methods, partial implementation" },
          { name: "Interfaces", description: "default methods, functional interfaces, sealed" },
        ],
      },
      {
        title: "Exception Handling & Generics",
        difficulty: "Intermediate",
        estimatedHours: 10,
        topics: [
          { name: "Exception Hierarchy", description: "Checked vs unchecked, Error vs Exception" },
          { name: "Try-Catch-Finally", description: "Multi-catch, try-with-resources, stack traces" },
          { name: "Custom Exceptions", description: "Creating exception classes, best practices" },
          { name: "Generics", description: "Type parameters, bounded types, wildcards, erasure" },
        ],
      },
      {
        title: "Collections Framework",
        difficulty: "Intermediate",
        estimatedHours: 12,
        topics: [
          { name: "List Implementations", description: "ArrayList, LinkedList, Vector, CopyOnWriteArrayList" },
          { name: "Set & Map", description: "HashSet, TreeSet, HashMap, TreeMap, LinkedHash*" },
          { name: "Queue & Deque", description: "PriorityQueue, ArrayDeque, BlockingQueue" },
          { name: "Iterators", description: "Iterator, ListIterator, Iterable interface" },
          { name: "Collections Utility", description: "sort, shuffle, synchronizedList, unmodifiable" },
        ],
      },
      {
        title: "Java Streams & Lambdas",
        difficulty: "Advanced",
        estimatedHours: 10,
        topics: [
          { name: "Lambda Expressions", description: "Syntax, functional interfaces, method references" },
          { name: "Stream API", description: "filter, map, reduce, collect, flatMap" },
          { name: "Optional", description: "Avoiding null, map, flatMap, orElse" },
          { name: "Functional Interfaces", description: "Predicate, Function, Consumer, Supplier" },
        ],
      },
      {
        title: "Concurrency & I/O",
        difficulty: "Advanced",
        estimatedHours: 14,
        topics: [
          { name: "Threads", description: "Thread class, Runnable, lifecycle, daemon threads" },
          { name: "Synchronization", description: "synchronized, volatile, locks, deadlock" },
          { name: "Executor Framework", description: "ExecutorService, Future, CompletableFuture" },
          { name: "File I/O (NIO.2)", description: "Path, Files, Streams, watching file changes" },
          { name: "Serialization", description: "Serializable, Externalizable, transient" },
        ],
      },
      {
        title: "Advanced Java & Ecosystem",
        difficulty: "Advanced",
        estimatedHours: 20,
        topics: [
          { name: "Records & Sealed Classes", description: "Modern Java features (14+, 17+)" },
          { name: "Reflection & Annotations", description: "Runtime introspection, custom annotations" },
          { name: "JDBC & Databases", description: "Database connectivity, PreparedStatement, transactions" },
          { name: "Build Tools", description: "Maven, Gradle, dependency management" },
          { name: "Unit Testing", description: "JUnit 5, Mockito, assertions, test lifecycle" },
        ],
      },
    ],
  },
  {
    id: "cpp",
    name: "C++",
    icon: "⚡",
    color: "#00599C",
    gradient: "from-blue-600 to-indigo-700",
    tagline: "Performance Meets Abstraction",
    description: "The language of game engines, system software, and high-frequency trading. C++ combines low-level power with high-level abstractions.",
    prerequisites: ["C programming basics", "Understanding of memory management"],
    totalHours: 110,
    modules: [
      {
        title: "C++ Foundations",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: "C++ vs C", description: "Evolution, standards C++11/14/17/20/23" },
          { name: "I/O Streams", description: "cin, cout, cerr, stream manipulators" },
          { name: "Namespaces", description: "std namespace, creating namespaces, using directive" },
          { name: "References", description: "Lvalue references, const references, vs pointers" },
          { name: "auto & Type Deduction", description: "auto keyword, decltype, structured bindings" },
        ],
      },
      {
        title: "OOP in C++",
        difficulty: "Intermediate",
        estimatedHours: 14,
        topics: [
          { name: "Classes", description: "Access specifiers, constructors, destructors" },
          { name: "Copy Semantics", description: "Copy constructor, copy assignment, Rule of Three" },
          { name: "Move Semantics", description: "Rvalue references, std::move, Rule of Five" },
          { name: "Inheritance", description: "Public/protected/private, virtual, abstract classes" },
          { name: "Operator Overloading", description: "Arithmetic, comparison, stream operators" },
          { name: "Friend Functions", description: "Friend classes, access control patterns" },
        ],
      },
      {
        title: "Templates & STL",
        difficulty: "Intermediate",
        estimatedHours: 14,
        topics: [
          { name: "Function Templates", description: "Template syntax, specialization, overloading" },
          { name: "Class Templates", description: "Template classes, partial specialization" },
          { name: "STL Containers", description: "vector, list, deque, map, set, unordered_*" },
          { name: "STL Algorithms", description: "sort, find, transform, accumulate, ranges" },
          { name: "Iterators", description: "Categories, iterator adapters, custom iterators" },
        ],
      },
      {
        title: "Memory & Smart Pointers",
        difficulty: "Advanced",
        estimatedHours: 12,
        topics: [
          { name: "Dynamic Memory", description: "new/delete, arrays, placement new" },
          { name: "Smart Pointers", description: "unique_ptr, shared_ptr, weak_ptr, make_unique" },
          { name: "RAII", description: "Resource management, scope-based cleanup" },
          { name: "Memory Model", description: "Stack vs heap, alignment, cache efficiency" },
        ],
      },
      {
        title: "Modern C++ Features",
        difficulty: "Advanced",
        estimatedHours: 14,
        topics: [
          { name: "Lambda Expressions", description: "Captures, generic lambdas, mutable" },
          { name: "Concurrency", description: "std::thread, mutex, async, futures, atomics" },
          { name: "Variadic Templates", description: "Parameter packs, fold expressions" },
          { name: "Concepts (C++20)", description: "Constraints, requires clauses" },
          { name: "Coroutines (C++20)", description: "co_await, co_yield, co_return" },
          { name: "Modules (C++20)", description: "import/export, replacing headers" },
        ],
      },
      {
        title: "Advanced C++ Topics",
        difficulty: "Advanced",
        estimatedHours: 16,
        topics: [
          { name: "Exception Safety", description: "noexcept, exception guarantees, RAII" },
          { name: "Metaprogramming", description: "constexpr, consteval, type traits, SFINAE" },
          { name: "Design Patterns", description: "Singleton, Factory, Observer, CRTP" },
          { name: "Build Systems", description: "CMake, dependency management, packages" },
          { name: "Performance Profiling", description: "Benchmarking, cache optimization, SIMD" },
        ],
      },
    ],
  },
  {
    id: "javascript",
    name: "JavaScript",
    icon: "🌐",
    color: "#F7DF1E",
    gradient: "from-yellow-400 to-orange-500",
    tagline: "The Language of the Web",
    description: "Power the entire web stack — from interactive frontends to scalable backends with Node.js. The most widely-used language in the world.",
    prerequisites: ["Basic HTML & CSS knowledge"],
    totalHours: 85,
    modules: [
      {
        title: "JavaScript Basics",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: "Variables & Types", description: "let, const, var, primitives, typeof" },
          { name: "Operators & Expressions", description: "Arithmetic, comparison, logical, nullish coalescing" },
          { name: "Strings & Template Literals", description: "Methods, interpolation, tagged templates" },
          { name: "Control Flow", description: "if-else, switch, ternary, loops" },
          { name: "Functions", description: "Declarations, expressions, arrow functions, IIFE" },
        ],
      },
      {
        title: "Data Structures",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: "Arrays", description: "Methods, destructuring, spread, rest" },
          { name: "Objects", description: "Literals, computed properties, shorthand, Object.*" },
          { name: "Map & Set", description: "WeakMap, WeakSet, use cases" },
          { name: "JSON", description: "Parsing, stringifying, structured clone" },
        ],
      },
      {
        title: "Advanced Functions",
        difficulty: "Intermediate",
        estimatedHours: 10,
        topics: [
          { name: "Closures & Scope", description: "Lexical scope, closure patterns, memory" },
          { name: "this Keyword", description: "Binding rules, call, apply, bind" },
          { name: "Prototypes", description: "Prototype chain, __proto__, Object.create" },
          { name: "Higher-Order Functions", description: "map, filter, reduce, currying, composition" },
        ],
      },
      {
        title: "OOP & Classes",
        difficulty: "Intermediate",
        estimatedHours: 8,
        topics: [
          { name: "ES6 Classes", description: "Constructor, methods, static, private fields" },
          { name: "Inheritance", description: "extends, super, mixins" },
          { name: "Symbols & Iterators", description: "Symbol.iterator, custom iterables" },
          { name: "Proxy & Reflect", description: "Metaprogramming, traps, handlers" },
        ],
      },
      {
        title: "Async JavaScript",
        difficulty: "Intermediate",
        estimatedHours: 12,
        topics: [
          { name: "Callbacks & Event Loop", description: "Call stack, task queue, microtasks" },
          { name: "Promises", description: "Creating, chaining, Promise.all, Promise.race" },
          { name: "Async/Await", description: "Syntax, error handling, parallel execution" },
          { name: "Fetch API", description: "HTTP requests, headers, AbortController" },
          { name: "Web Workers", description: "Background threads, SharedArrayBuffer" },
        ],
      },
      {
        title: "DOM & Browser APIs",
        difficulty: "Intermediate",
        estimatedHours: 10,
        topics: [
          { name: "DOM Manipulation", description: "Selecting, creating, modifying elements" },
          { name: "Events", description: "Listeners, bubbling, delegation, custom events" },
          { name: "Storage APIs", description: "localStorage, sessionStorage, IndexedDB" },
          { name: "Canvas & Animation", description: "2D drawing, requestAnimationFrame" },
        ],
      },
      {
        title: "Modern JavaScript & Tooling",
        difficulty: "Advanced",
        estimatedHours: 12,
        topics: [
          { name: "ES Modules", description: "import/export, dynamic imports, tree shaking" },
          { name: "Error Handling Patterns", description: "Custom errors, error boundaries, retry logic" },
          { name: "Testing", description: "Jest, Vitest, testing patterns, mocking" },
          { name: "Build Tools", description: "Vite, Webpack, Babel, ESLint, Prettier" },
          { name: "Node.js Basics", description: "Runtime, npm, Express, file system" },
        ],
      },
    ],
  },
  {
    id: "typescript",
    name: "TypeScript",
    icon: "🔷",
    color: "#3178C6",
    gradient: "from-blue-500 to-blue-700",
    tagline: "JavaScript with Superpowers",
    description: "Add type safety to JavaScript and catch errors before they happen. The industry standard for large-scale web applications.",
    prerequisites: ["Solid JavaScript knowledge", "ES6+ features"],
    totalHours: 60,
    modules: [
      {
        title: "TypeScript Essentials",
        difficulty: "Beginner",
        estimatedHours: 8,
        topics: [
          { name: "Setup & Configuration", description: "tsconfig.json, compiler options, strict mode" },
          { name: "Basic Types", description: "string, number, boolean, arrays, tuples, enums" },
          { name: "Type Annotations", description: "Variables, function params, return types" },
          { name: "Union & Intersection", description: "Union types, intersection types, type narrowing" },
        ],
      },
      {
        title: "Interfaces & Type Aliases",
        difficulty: "Beginner",
        estimatedHours: 8,
        topics: [
          { name: "Interfaces", description: "Object shapes, optional, readonly, extending" },
          { name: "Type Aliases", description: "Complex types, template literal types" },
          { name: "Type Guards", description: "typeof, instanceof, in, custom type guards" },
          { name: "Discriminated Unions", description: "Tagged unions, exhaustive checking" },
        ],
      },
      {
        title: "Generics",
        difficulty: "Intermediate",
        estimatedHours: 10,
        topics: [
          { name: "Generic Functions", description: "Type parameters, constraints, defaults" },
          { name: "Generic Classes", description: "Generic containers, inheritance patterns" },
          { name: "Utility Types", description: "Partial, Required, Pick, Omit, Record, Readonly" },
          { name: "Mapped & Conditional", description: "Mapped types, conditional types, infer" },
        ],
      },
      {
        title: "Advanced Types",
        difficulty: "Advanced",
        estimatedHours: 12,
        topics: [
          { name: "Template Literal Types", description: "String manipulation at type level" },
          { name: "Recursive Types", description: "Self-referencing types, deep partial" },
          { name: "Declaration Files", description: ".d.ts files, DefinitelyTyped, ambient modules" },
          { name: "Module Augmentation", description: "Extending third-party types, global augmentation" },
          { name: "Decorators", description: "Stage 3 decorators, metadata, reflect-metadata" },
        ],
      },
      {
        title: "TypeScript in Practice",
        difficulty: "Advanced",
        estimatedHours: 10,
        topics: [
          { name: "React with TypeScript", description: "Component types, hooks, context, generics" },
          { name: "Node.js with TypeScript", description: "Express typing, tsnode, build patterns" },
          { name: "Testing TypeScript", description: "Type testing, vitest, jest integration" },
          { name: "Migration Strategies", description: "Gradual migration, strict mode adoption" },
        ],
      },
    ],
  },
  {
    id: "csharp",
    name: "C#",
    icon: "💎",
    color: "#239120",
    gradient: "from-green-500 to-purple-600",
    tagline: "Elegant & Enterprise-Ready",
    description: "Build desktop apps, web services, games with Unity, and cloud-native applications. C# blends power with developer productivity.",
    prerequisites: ["Basic programming concepts", "Understanding of OOP"],
    totalHours: 95,
    modules: [
      {
        title: "C# Fundamentals",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: ".NET Ecosystem", description: ".NET 8+, CLR, assemblies, NuGet" },
          { name: "Data Types & Variables", description: "Value vs reference, nullable, var, dynamic" },
          { name: "Control Flow", description: "if, switch expressions, pattern matching" },
          { name: "Methods", description: "Parameters (ref, out, in), overloading, expression-bodied" },
        ],
      },
      {
        title: "OOP in C#",
        difficulty: "Intermediate",
        estimatedHours: 14,
        topics: [
          { name: "Classes & Records", description: "Properties, auto-properties, init, records" },
          { name: "Inheritance & Interfaces", description: "Abstract, virtual, sealed, default implementations" },
          { name: "Generics", description: "Constraints, covariance, contravariance" },
          { name: "Events & Delegates", description: "Event pattern, multicast, Action, Func" },
          { name: "Operator Overloading", description: "Custom operators, implicit/explicit conversion" },
        ],
      },
      {
        title: "Collections & LINQ",
        difficulty: "Intermediate",
        estimatedHours: 12,
        topics: [
          { name: "Collections", description: "List, Dictionary, HashSet, Queue, Stack" },
          { name: "LINQ Queries", description: "Query syntax, method syntax, deferred execution" },
          { name: "LINQ Operations", description: "Where, Select, Join, GroupBy, Aggregate" },
          { name: "IEnumerable & IQueryable", description: "Iteration patterns, expression trees" },
        ],
      },
      {
        title: "Async & Advanced C#",
        difficulty: "Advanced",
        estimatedHours: 14,
        topics: [
          { name: "Async/Await", description: "Task, ValueTask, cancellation tokens, deadlocks" },
          { name: "Pattern Matching", description: "Type, property, positional, list patterns" },
          { name: "Span & Memory", description: "Span<T>, Memory<T>, ArrayPool, performance" },
          { name: "Source Generators", description: "Compile-time code generation" },
          { name: "Unit Testing", description: "xUnit, NUnit, Moq, FluentAssertions" },
        ],
      },
    ],
  },
  {
    id: "go",
    name: "Go",
    icon: "🦫",
    color: "#00ADD8",
    gradient: "from-cyan-500 to-blue-500",
    tagline: "Simple, Fast, Concurrent",
    description: "Google's language built for cloud infrastructure, microservices, and concurrent systems. Go's simplicity enables teams to build and deploy at scale.",
    prerequisites: ["Basic programming knowledge", "Command line familiarity"],
    totalHours: 65,
    modules: [
      {
        title: "Go Fundamentals",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: "Go Setup & Basics", description: "Go toolchain, workspace, go mod, Hello World" },
          { name: "Types & Variables", description: "Basic types, zero values, short declarations" },
          { name: "Control Flow", description: "if, for, switch, defer, panic, recover" },
          { name: "Functions", description: "Multiple returns, named returns, variadic, closures" },
        ],
      },
      {
        title: "Data Structures & OOP",
        difficulty: "Intermediate",
        estimatedHours: 12,
        topics: [
          { name: "Arrays & Slices", description: "make, append, slice internals, copy" },
          { name: "Maps", description: "Creation, iteration, comma ok pattern" },
          { name: "Structs", description: "Definition, embedding, methods, pointer receivers" },
          { name: "Interfaces", description: "Implicit implementation, empty interface, type assertions" },
        ],
      },
      {
        title: "Concurrency",
        difficulty: "Advanced",
        estimatedHours: 14,
        topics: [
          { name: "Goroutines", description: "Launching, synchronization, WaitGroup" },
          { name: "Channels", description: "Buffered, unbuffered, directional, select" },
          { name: "Patterns", description: "Fan-in/fan-out, pipeline, worker pools" },
          { name: "sync Package", description: "Mutex, RWMutex, Once, atomic operations" },
          { name: "Context", description: "Cancellation, timeouts, value propagation" },
        ],
      },
      {
        title: "Standard Library & Web",
        difficulty: "Advanced",
        estimatedHours: 14,
        topics: [
          { name: "Error Handling", description: "error interface, wrapping, errors.Is, errors.As" },
          { name: "net/http", description: "Handlers, middleware, routing, templates" },
          { name: "Encoding", description: "json, xml, gob, struct tags" },
          { name: "Testing", description: "testing package, benchmarks, table-driven tests" },
          { name: "Generics (1.18+)", description: "Type parameters, constraints, comparable" },
        ],
      },
    ],
  },
  {
    id: "rust",
    name: "Rust",
    icon: "🦀",
    color: "#CE422B",
    gradient: "from-orange-600 to-red-700",
    tagline: "Fearless Systems Programming",
    description: "Memory safety without garbage collection. Rust prevents entire classes of bugs at compile time while delivering C/C++ level performance.",
    prerequisites: ["C/C++ familiarity", "Systems programming concepts"],
    totalHours: 100,
    modules: [
      {
        title: "Rust Fundamentals",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: "Cargo & Setup", description: "Rust toolchain, cargo new, crates.io, rustup" },
          { name: "Variables & Mutability", description: "let, mut, shadowing, constants" },
          { name: "Data Types", description: "Scalars, compounds, tuples, arrays" },
          { name: "Control Flow", description: "if expressions, loop, while, for, pattern matching" },
          { name: "Functions", description: "Statements, expressions, return values" },
        ],
      },
      {
        title: "Ownership & Borrowing",
        difficulty: "Intermediate",
        estimatedHours: 14,
        topics: [
          { name: "Ownership Rules", description: "Move semantics, Copy trait, Drop" },
          { name: "References & Borrowing", description: "Immutable/mutable refs, NLL" },
          { name: "Lifetimes", description: "Lifetime annotations, elision, static lifetime" },
          { name: "Slices", description: "String slices, array slices, slice patterns" },
        ],
      },
      {
        title: "Enums, Structs & Pattern Matching",
        difficulty: "Intermediate",
        estimatedHours: 12,
        topics: [
          { name: "Structs", description: "Named, tuple, unit structs, methods, impl" },
          { name: "Enums", description: "Variants with data, Option, Result" },
          { name: "Pattern Matching", description: "match, if let, while let, destructuring" },
          { name: "Error Handling", description: "Result, ?, panic!, custom error types, thiserror" },
        ],
      },
      {
        title: "Generics, Traits & Collections",
        difficulty: "Advanced",
        estimatedHours: 14,
        topics: [
          { name: "Generics", description: "Functions, structs, enums, monomorphization" },
          { name: "Traits", description: "Defining, implementing, trait bounds, dyn" },
          { name: "Collections", description: "Vec, HashMap, HashSet, BTreeMap, VecDeque" },
          { name: "Iterators", description: "Iterator trait, adaptors, collect, IntoIterator" },
          { name: "Closures", description: "Fn, FnMut, FnOnce, move closures" },
        ],
      },
      {
        title: "Advanced Rust",
        difficulty: "Advanced",
        estimatedHours: 16,
        topics: [
          { name: "Concurrency", description: "threads, channels, Arc, Mutex, Send, Sync" },
          { name: "Async Rust", description: "async/await, tokio, futures, pinning" },
          { name: "Unsafe Rust", description: "Raw pointers, FFI, unsafe traits" },
          { name: "Macros", description: "Declarative macros, procedural macros, derive" },
          { name: "Smart Pointers", description: "Box, Rc, RefCell, Cow, Pin" },
          { name: "Testing & Tooling", description: "cargo test, clippy, rustfmt, docs" },
        ],
      },
    ],
  },
  {
    id: "ruby",
    name: "Ruby",
    icon: "💠",
    color: "#CC342D",
    gradient: "from-red-500 to-pink-600",
    tagline: "Optimized for Developer Happiness",
    description: "Elegant, expressive, and productive. Ruby powers rapid web development with Rails and excels at scripting and automation tasks.",
    prerequisites: ["Basic programming concepts"],
    totalHours: 60,
    modules: [
      {
        title: "Ruby Basics",
        difficulty: "Beginner",
        estimatedHours: 10,
        topics: [
          { name: "Ruby Philosophy", description: "Everything is an object, conventions, irb/pry" },
          { name: "Variables & Types", description: "Strings, integers, floats, symbols, nil" },
          { name: "Control Flow", description: "if/unless, case/when, while/until, ternary" },
          { name: "Methods", description: "def, arguments, default values, return, blocks" },
        ],
      },
      {
        title: "Collections & Iterators",
        difficulty: "Beginner",
        estimatedHours: 8,
        topics: [
          { name: "Arrays & Hashes", description: "Creation, methods, nested structures" },
          { name: "Blocks, Procs & Lambdas", description: "yield, Proc.new, lambda, ->() syntax" },
          { name: "Enumerable", description: "map, select, reject, reduce, each_with_object" },
          { name: "Ranges", description: "Inclusive, exclusive, step, membership" },
        ],
      },
      {
        title: "OOP in Ruby",
        difficulty: "Intermediate",
        estimatedHours: 10,
        topics: [
          { name: "Classes & Objects", description: "initialize, attr_*, instance/class variables" },
          { name: "Inheritance & Modules", description: "Mixins, include, extend, prepend" },
          { name: "Method Missing", description: "Dynamic dispatch, respond_to_missing?" },
          { name: "Comparable & Enumerable", description: "Custom sorting, iteration protocols" },
        ],
      },
      {
        title: "Advanced Ruby",
        difficulty: "Advanced",
        estimatedHours: 12,
        topics: [
          { name: "Metaprogramming", description: "define_method, method_missing, open classes" },
          { name: "Regular Expressions", description: "Patterns, captures, gsub, scan" },
          { name: "File I/O & Networking", description: "File, Dir, Net::HTTP, sockets" },
          { name: "Error Handling", description: "begin/rescue/ensure, retry, custom exceptions" },
          { name: "Testing", description: "RSpec, Minitest, TDD workflow, factories" },
          { name: "Gems & Bundler", description: "Dependency management, creating gems" },
        ],
      },
    ],
  },
];
